---
# tasks for PowerMTA configuration on the Windows host


#- name: Include role specific variables
#  include_vars: main.yml

- name: Ping the server
  win_ping:

- name: Creates a folder for the config file to be stored
  win_file:
    path: c:\Temp\
    state: directory


- name: Create a file from Jinja2 template
  win_template:
    src: config.ini.j2
    dest: C:\temp\config.ini
    newline_sequence: '\r\n'

    
  
